name: Node CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Настройка Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # Запуск линтера
      - name: Run lint
        run: npx eslint .

      # Запуск тестов
      - name: Run tests
        run: npm test -- --coverage --coverageProvider=v8

      # Отправка отчета покрытия в CodeClimate через Quality.sh
      - name: Upload coverage to CodeClimate
        run: |
          curl -sSL https://github.com/qlty-sh/codeclimate-action/releases/latest/download/qlty-test-reporter-linux-amd64 -o /tmp/qlty-test-reporter
          chmod +x /tmp/qlty-test-reporter
          /tmp/qlty-test-reporter after-build --coverage-input-type lcov --coverage-input-path coverage/lcov-report.json
        env:
          QCLTY_TEST_REPORTER_ID: ${{ secrets.QCLTY_TEST_REPORTER_ID }}
